### ISSUE TITLE
Invalid render for 2.7" GDEW027W3 display

### ISSUE THREAD

**Issue by lyusupov** [martinberlin/eink-calendar#14]
**Hardware**: TTGO T5S ( SoftRF [**SkyView EZ**](https://github.com/lyusupov/SoftRF/wiki/SkyView-EZ) )
**Software**: up to date [cale_t5](https://github.com/martinberlin/eink-calendar/tree/cale_t5) branch

Config.h:

```
//#define GDEH0213B73
#define GDEW027W3    // 2.7" b/w

```

main.cpp:

```
  #elif defined(GDEW027W3)
  #include <GxGDEW027W3/GxGDEW027W3.h>
#endif
```

When I select the 2.7 inch display on cale.es :

![image](https://user-images.githubusercontent.com/5849637/76309513-f5d6a200-62dd-11ea-87c3-ca886808105e.png)

rendered picture is this one:

![image](https://user-images.githubusercontent.com/5849637/76309576-1bfc4200-62de-11ea-8ed9-ca68eeaf84cf.png)

this is ENABLE_IMAGE_DEBUG output:
```
->BMP starts here. File size: 6482
Image Offset: 146
Header size: 124
Width * Height: 264 x 176 / Bit Depth: 1
Planes: 1
Format: 0
Bytes read: 5842 BMP headers detected: 997 ms. BMP total fetch: 434 ms.  Total download: 1431 ms
display.update() render: 2519 ms.
Free heap: 250336
```

<br>
<br>

However, when I select **default** 2.13 inch display:

![image](https://user-images.githubusercontent.com/5849637/76309911-d12efa00-62de-11ea-8b4e-1c937568a14a.png)

The picture is getting better:

![image](https://user-images.githubusercontent.com/5849637/76309945-e6a42400-62de-11ea-8603-1c935253ab74.png)

You can see there that **picture does not fit to the screen size**.

This is  ENABLE_IMAGE_DEBUG output:

```
->BMP starts here. File size: 4050
Image Offset: 146
Header size: 124
Width * Height: 250 x 122 / Bit Depth: 1
Planes: 1
Format: 0
Bytes read: 3938 BMP headers detected: 1034 ms. BMP total fetch: 1285 ms.  Total download: 2319 ms
display.update() render: 2520 ms.
Free heap: 250340
```

**Comment by martinberlin** [comment]
Thanks for your report. 
Please try in "Render Screen" the option:  4 bit
![CALE Integrations(1)](https://user-images.githubusercontent.com/2692928/76401508-443d7c80-6382-11ea-8752-c8d9e02450ff.png)

For some screen sizes there is a bug rendering the image with one bit.

**Comment by lyusupov** [comment]
Yes, the '4 bit' color depth setting fixes the issue.

```
->BMP starts here. File size: 23434
Image Offset: 202
Header size: 124
Width * Height: 264 x 176 / Bit Depth: 4
Planes: 1
Format: 0
Bytes read: 23266 BMP headers detected: 1371 ms. BMP total fetch: 1580 ms.  Total download: 2951 ms
display.update() render: 2518 ms.
Free heap: 250332

```

![image](https://user-images.githubusercontent.com/5849637/76404991-8376c800-6398-11ea-8d49-8a4d4f7b046b.png)

<br>
<br>

### Thank you very much for your prompt response!

<br>
<br>

**Comment by martinberlin** [comment]
Just for the record: 
I did an update today in the master branch after two days of testing:
https://github.com/martinberlin/eink-calendar/commit/e8ddbcd72c7ae334d5a67f2b35f6d5c60bfc317f#diff-7ec3c68a81efff79b6ca22ac1f1eabba

Now it should work also using 1 bit depth. I just need need to port this function to the T5 branch and test, will do it tomorrow and if you hae time you can try it out!

**Comment by lyusupov** [comment]
Martin, thank you for the status update!

I'll keep monitoring cale_t5 branch and will test the function as soon as practicable.
I'll let you know if it works on 2.7" B&W (T5S) or not.

**Comment by lyusupov** [comment]
Martin, I've left my comment there:
https://github.com/martinberlin/eink-calendar/commit/db19562c653926fc652696ab02f77ddd3feeb707#commitcomment-38095463

**Comment by martinberlin** [comment]
Thanks great that now is better. If you have any recommendation more just report in the new "Get support" area. We are looking to bring at least 20 users more in May to see if we can escalate the screenshot microservice properly.
