### ISSUE TITLE
Fail to build t5s with GDEW027C44 screen

### ISSUE THREAD

**Issue by kalon33** [martinberlin/eink-calendar#18]
When trying to build for t5s with GDEW027C44 e-ink screen in platformio, I got an error, here's the log:
   
```
> Executing task: platformio run <

Processing lolin_d32 (platform: espressif32@1.11.1; board: lolin_d32; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin_d32.html
PLATFORM: Espressif 32 (1.11.1) > WEMOS LOLIN D32
HARDWARE: ESP32 160MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 2.10004.191002 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <GxEPD> 3.1.0
|   |-- <SPI> 1.0
|   |-- <Adafruit GFX Library> 1.10.0
|   |   |-- <Adafruit BusIO> 1.4.1
|   |   |   |-- <Wire> 1.0.1
|   |   |   |-- <SPI> 1.0
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|-- <Adafruit GFX Library> 1.10.0
|   |-- <Adafruit BusIO> 1.4.1
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|-- <Button2> 1.0.0+sha.fed9e73
|-- <ESP8266Audio> 1.5.1+sha.93a540d
|   |-- <SPI> 1.0
|   |-- <FS> 1.0
|   |-- <SPIFFS> 1.0
|   |   |-- <FS> 1.0
|   |-- <HTTPClient> 1.2
|   |   |-- <WiFi> 1.0
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.0
|   |-- <SD(esp32)> 1.0.5
|   |   |-- <FS> 1.0
|   |   |-- <SPI> 1.0
|-- <Adafruit BusIO> 1.4.1
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|-- <Wire> 1.0.1
|-- <HTTPClient> 1.2
|   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|-- <SD(esp32)> 1.0.5
|   |-- <FS> 1.0
|   |-- <SPI> 1.0
|-- <SPIFFS> 1.0
|   |-- <FS> 1.0
|-- <Config>
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <SPI> 1.0
|-- <WiFi> 1.0
Building in release mode
Compiling .pio/build/lolin_d32/src/main.cpp.o
Archiving .pio/build/lolin_d32/lib633/libWire.a
Indexing .pio/build/lolin_d32/lib633/libWire.a
Archiving .pio/build/lolin_d32/libc06/libAdafruit BusIO.a
Indexing .pio/build/lolin_d32/libc06/libAdafruit BusIO.a
Compiling .pio/build/lolin_d32/libee3/Adafruit GFX Library/glcdfont.c.o
Compiling .pio/build/lolin_d32/lib087/GxEPD/GxEPD.cpp.o
Compiling .pio/build/lolin_d32/lib087/GxEPD/GxFont_GFX.cpp.o
Compiling .pio/build/lolin_d32/lib087/GxEPD/GxGDE0213B1/GxGDE0213B1.cpp.o
Compiling .pio/build/lolin_d32/lib087/GxEPD/GxGDEH0154D67/GxGDEH0154D67.cpp.o
Archiving .pio/build/lolin_d32/libee3/libAdafruit GFX Library.a
Compiling .pio/build/lolin_d32/lib087/GxEPD/GxGDEH0213B72/GxGDEH0213B72.cpp.o
Compiling .pio/build/lolin_d32/lib087/GxEPD/GxGDEH0213B73/GxGDEH0213B73.cpp.o
Indexing .pio/build/lolin_d32/libee3/libAdafruit GFX Library.a
Compiling .pio/build/lolin_d32/lib087/GxEPD/GxGDEH029A1/GxGDEH029A1.cpp.o
src/main.cpp:100:1: error: 'GxEPD_Class' does not name a type
 GxEPD_Class display(io, EINK_RST, EINK_BUSY );
 ^
src/main.cpp: In function 'void displayInit()':
src/main.cpp:119:5: error: 'display' was not declared in this scope
     display.init(115200);
     ^
src/main.cpp: In function 'void displayMessage(String, int)':
src/main.cpp:132:3: error: 'display' was not declared in this scope
   display.setTextColor(GxEPD_WHITE);
   ^
src/main.cpp: In function 'void displayClean()':
src/main.cpp:141:3: error: 'display' was not declared in this scope
   display.fillScreen(GxEPD_WHITE);
   ^
src/main.cpp: In function 'uint32_t skip(WiFiClient&, int32_t)':
src/main.cpp:154:15: warning: unused variable 'v' [-Wunused-variable]
       int16_t v = client.read();
               ^
src/main.cpp: In function 'bool parsePathInformation(char*, char**, char*, unsigned int*, bool*)':
src/main.cpp:241:27: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
     host[hostname_length] = NULL;
                           ^
src/main.cpp: In function 'void handleWebToDisplay(char*, String, bool)':
src/main.cpp:306:3: error: 'display' was not declared in this scope
   display.fillScreen(GxEPD_WHITE);
   ^
src/main.cpp:427:58: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
             uint32_t got = read(client, input_buffer, get);
                                                          ^
src/main.cpp:163:10: note: candidate 1: uint32_t read(WiFiClient&, uint8_t*, int32_t)
 uint32_t read(WiFiClient& client, uint8_t* buffer, int32_t bytes)
          ^
In file included from /home/nicolas/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/stdlib.h:11:0,
                 from /home/nicolas/.platformio/packages/framework-arduinoespressif32/cores/esp32/WString.h:26,
                 from lib/Config/Config.h:1,
                 from src/main.cpp:1:
/home/nicolas/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/sys/unistd.h:149:32: note: candidate 2: int read(int, void*, size_t)
 _READ_WRITE_RETURN_TYPE _EXFUN(read, (int __fd, void *__buf, size_t __nbyte ));
                                ^
/home/nicolas/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/_ansi.h:65:30: note: in definition of macro '_EXFUN'
 #define _EXFUN(name, proto)  name proto
                              ^
src/main.cpp:431:76: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
               uint32_t gotmore = read(client, input_buffer + got, get - got);
                                                                            ^
src/main.cpp:163:10: note: candidate 1: uint32_t read(WiFiClient&, uint8_t*, int32_t)
 uint32_t read(WiFiClient& client, uint8_t* buffer, int32_t bytes)
          ^
In file included from /home/nicolas/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/stdlib.h:11:0,
                 from /home/nicolas/.platformio/packages/framework-arduinoespressif32/cores/esp32/WString.h:26,
                 from lib/Config/Config.h:1,
                 from src/main.cpp:1:
/home/nicolas/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/sys/unistd.h:149:32: note: candidate 2: int read(int, void*, size_t)
 _READ_WRITE_RETURN_TYPE _EXFUN(read, (int __fd, void *__buf, size_t __nbyte ));
                                ^
/home/nicolas/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/_ansi.h:65:30: note: in definition of macro '_EXFUN'
 #define _EXFUN(name, proto)  name proto
                              ^
src/main.cpp:509:77: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t {aka unsigned int}' [-Wformat=]
     bytes_read,millisBmp-millisIni, millisEnd-millisBmp, millisEnd-millisIni);
                                                                             ^
src/main.cpp:341:14: warning: unused variable 'creatorBytes' [-Wunused-variable]
     uint32_t creatorBytes = read32(client);
              ^
src/main.cpp:274:12: warning: unused variable 'startTime' [-Wunused-variable]
   uint32_t startTime = millis();
            ^
src/main.cpp: In function 'void loop()':
src/main.cpp:677:7: error: 'display' was not declared in this scope
       display.powerDown();
       ^
*** [.pio/build/lolin_d32/src/main.cpp.o] Error 1
================================================================================ [FAILED] Took 3.42 seconds ================================================================================
The terminal process "platformio 'run'" terminated with exit code: 1.
```
When I replace the proper define with another screen (for example GDEW027W3), it builds properly (but screen doesn't work of course...)

An idea how to fix this?

**Comment by martinberlin** [comment]
Hello @kalon33 
I just pulled master from zero, found one error, but it's about this library:
Compiling .pio/build/lolin_d32/libd7c/GxEPD/GxEPD.cpp.o
In file included from .pio/libdeps/lolin_d32/Adafruit GFX Library/Adafruit_GrayOLED.cpp:20:0:
.pio/libdeps/lolin_d32/Adafruit GFX Library/Adafruit_GrayOLED.h:30:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

Just deleted Adafruit_GrayOLED header and cpp file. 

I copied: Config.h.dist  > Config.h and just uncommented: 

#define GDEW027C44   // 2.7" b/w/r

And updated: EINK_HAS_COLOR to true

I hit on build and it compiles:
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  23.2% (used 75916 bytes from 327680 bytes)
Flash: [==========]  99.2% (used 1560518 bytes from 1572864 bytes)
esptool.py v2.6
==================================================== [SUCCESS] Took 72.07 seconds

Try deleting the library folder completely: .pio/libdeps/lolin_d32/GxEPD  and let it download again. 
For me it looks that it's not finding the include of GxEPD but it should be there if you check the library folders.

In another topic:
PLATFORM: Espressif 32 (1.11.1) > WEMOS LOLIN D32  >Your framework looks outdated

Mine reports: 
PLATFORM: Espressif 32 (1.12.4) > WEMOS LOLIN D32

Just go to Platformio logo -> Platforms -> Updates 
And update the Espressif32 framework to last version (Just in case)

**Comment by gorzynsk** [comment]
I get 

`> Executing task: C:\Users\gorzy\.platformio\penv\Scripts\pio.exe run <

Processing lolin_d32 (platform: espressif32@1.11.1; board: lolin_d32; framework: arduino)
----------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin_d32.html       
PLATFORM: Espressif 32 (1.11.1) > WEMOS LOLIN D32
HARDWARE: ESP32 160MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)        
PACKAGES:
 - framework-arduinoespressif32 2.10004.191002 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing git+https://github.com/ZinggJM/GxEPD.git
git version 2.27.0.windows.1
Cloning into 'C:\Users\gorzy\.platformio\.cache\tmp\pkg-installing-sf6kmhnx'...
Library Manager: GxEPD @ 3.1.0+sha.39621c2 has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing Adafruit GFX Library
Library Manager: Adafruit GFX Library @ 1.10.3 has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing Adafruit BusIO
Library Manager: Adafruit BusIO @ 1.7.0 has been installed!
Library Manager: Installing git+https://github.com/adafruit/Adafruit-GFX-Library.git    
git version 2.27.0.windows.1
Cloning into 'C:\Users\gorzy\.platformio\.cache\tmp\pkg-installing-0wkdeipb'...
Library Manager: Adafruit GFX Library @ 1.10.3+sha.58606c5 has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing git+https://github.com/lewisxhe/Button2.git
git version 2.27.0.windows.1
Cloning into 'C:\Users\gorzy\.platformio\.cache\tmp\pkg-installing-78scueim'...
Library Manager: Button2 @ 1.0.0+sha.1d44a26 has been installed!
Library Manager: Installing git+https://github.com/earlephilhower/ESP8266Audio.git      
git version 2.27.0.windows.1
Cloning into 'C:\Users\gorzy\.platformio\.cache\tmp\pkg-installing-2ffn24na'...
Library Manager: ESP8266Audio @ 1.7.0+sha.dd8ac07 has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing SPI @ 1.0
Library Manager: Already installed, built-in library
Library Manager: Installing SPIFFS @ 1.0
Library Manager: Already installed, built-in library
Library Manager: Installing HTTPClient @ 1.0
Library Manager: Warning! More than one package has been found by HTTPClient @ 1.0 requirements:
 - zlalanne/HttpClient @ 0.0.0-alpha+sha.dac246b21f
 - amcewen/HttpClient @ 2.2.0
 - mbed-kazushi2008/HTTPClient @ 0.0.0+sha.cf5d7427a9ec
 - mbed-kaizen/HTTPClient @ 0.0.0+sha.9ba72b4d7ffc
 - mbed-mamezu/HTTPClient @ 0.0.0+sha.62fac7f06c8d
 - mbed-wolfssl/HTTPClient @ 0.0.0+sha.76aa4f4021c1
 - mbed-macrum/HTTPClient @ 0.0.0-alpha+sha.87fb5dd782dc
 - mbed-vwochnik/HTTPClient @ 0.0.0+sha.9386b15b0820
 - mbed-donatien/HTTPClient @ 0.0.0+sha.277279a1891e
 - mbed-dshoneye/HTTPClient @ 0.0.0+sha.f94e8df3b95d
Library Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Library Manager: Already installed, built-in library
Library Manager: Installing WiFiClientSecure @ 1.0
Library Manager: Already installed, built-in library
Found 33 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <GxEPD> 3.1.0+sha.39621c2
|   |-- <SPI> 1.0
|   |-- <Adafruit GFX Library> 1.10.3+sha.58606c5
|   |   |-- <Wire> 1.0.1
|   |   |-- <SPI> 1.0
|-- <Adafruit GFX Library> 1.10.3+sha.58606c5
|   |-- <Wire> 1.0.1
|   |-- <SPI> 1.0
|-- <Button2> 1.0.0+sha.1d44a26
|-- <ESP8266Audio> 1.7.0+sha.dd8ac07
|   |-- <SPI> 1.0
|   |-- <SPIFFS> 1.0
|   |   |-- <FS> 1.0
|   |-- <HTTPClient> 1.2
|   |   |-- <WiFi> 1.0
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|   |-- <FS> 1.0
|   |-- <SD(esp32)> 1.0.5
|   |   |-- <FS> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Config>
|-- <SPI> 1.0
|-- <Wire> 1.0.1
|-- <HTTPClient> 1.2
|   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|-- <SD(esp32)> 1.0.5
|   |-- <FS> 1.0
|   |-- <SPI> 1.0
|-- <SPIFFS> 1.0
|   |-- <FS> 1.0
|-- <Config>
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <WiFi> 1.0
Building in release mode
Compiling .pio\build\lolin_d32\src\main.cpp.o
Compiling .pio\build\lolin_d32\libff5\Wire\Wire.cpp.o
Compiling .pio\build\lolin_d32\lib9a8\Adafruit GFX Library@src-ac08a74c2b277f63bd79d3b6a68484c8\Adafruit_GFX.cpp.o
Compiling .pio\build\lolin_d32\lib9a8\Adafruit GFX Library@src-ac08a74c2b277f63bd79d3b6a68484c8\Adafruit_GrayOLED.cpp.o
In file included from .pio\libdeps\lolin_d32\Adafruit GFX Library@src-ac08a74c2b277f63bd79d3b6a68484c8\Adafruit_GrayOLED.cpp:20:0:
.pio\libdeps\lolin_d32\Adafruit GFX Library@src-ac08a74c2b277f63bd79d3b6a68484c8\Adafruit_GrayOLED.h:30:32: fatal error: Adafruit_I2CDevice.h: No such file or directory        

****************************************************************************
* Looking for Adafruit_I2CDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Adafruit_I2CDevice.h"
* Web  > https://platformio.org/lib/search?query=header:Adafruit_I2CDevice.h
*
****************************************************************************

compilation terminated.
*** [.pio\build\lolin_d32\lib9a8\Adafruit GFX Library@src-ac08a74c2b277f63bd79d3b6a68484c8\Adafruit_GrayOLED.cpp.o] Error 1
src\main.cpp: In function 'uint32_t skip(WiFiClient&, int32_t)':
src\main.cpp:154:15: warning: unused variable 'v' [-Wunused-variable]
       int16_t v = client.read();
               ^
src\main.cpp: In function 'bool parsePathInformation(char*, char**, char*, unsigned int*, bool*)':
src\main.cpp:241:27: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
     host[hostname_length] = NULL;
                           ^
src\main.cpp: In function 'void handleWebToDisplay(char*, String, bool)':
src\main.cpp:427:58: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
             uint32_t got = read(client, input_buffer, get);
                                                          ^
src\main.cpp:163:10: note: candidate 1: uint32_t read(WiFiClient&, uint8_t*, int32_t)
 uint32_t read(WiFiClient& client, uint8_t* buffer, int32_t bytes)
          ^
In file included from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/stdlib.h:11:0,
                 from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/cores/esp32/WString.h:26,
                 from lib/Config/Config.h:1,
                 from src\main.cpp:1:
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/sys/unistd.h:149:32: note: candidate 2: int read(int, void*, size_t)   
 _READ_WRITE_RETURN_TYPE _EXFUN(read, (int __fd, void *__buf, size_t __nbyte ));        
                                ^
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/_ansi.h:65:30: note: in definition of macro '_EXFUN'
 #define _EXFUN(name, proto)  name proto
                              ^
src\main.cpp:431:76: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
               uint32_t gotmore = read(client, input_buffer + got, get - got);
                                                                            ^
src\main.cpp:163:10: note: candidate 1: uint32_t read(WiFiClient&, uint8_t*, int32_t)
 uint32_t read(WiFiClient& client, uint8_t* buffer, int32_t bytes)
          ^
In file included from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/stdlib.h:11:0,
                 from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/cores/esp32/WString.h:26,
                 from lib/Config/Config.h:1,
                 from src\main.cpp:1:
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/sys/unistd.h:149:32: note: candidate 2: int read(int, void*, size_t)   
 _READ_WRITE_RETURN_TYPE _EXFUN(read, (int __fd, void *__buf, size_t __nbyte ));        
                                ^
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/_ansi.h:65:30: note: in definition of macro '_EXFUN'
 #define _EXFUN(name, proto)  name proto
                              ^
src\main.cpp:509:77: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t {aka unsigned int}' [-Wformat=]
     bytes_read,millisBmp-millisIni, millisEnd-millisBmp, millisEnd-millisIni);
                                                                             ^
src\main.cpp:341:14: warning: unused variable 'creatorBytes' [-Wunused-variable]        
     uint32_t creatorBytes = read32(client);
              ^
src\main.cpp:274:12: warning: unused variable 'startTime' [-Wunused-variable]
   uint32_t startTime = millis();
            ^
src\main.cpp:494:28: warning: 'colored' may be used uninitialized in this function [-Wmaybe-uninitialized]
           else if (colored && with_color)
                            ^
src\main.cpp:490:11: warning: 'whitish' may be used uninitialized in this function [-Wmaybe-uninitialized]
           if (whitish)
           ^
============================= [FAILED] Took 53.89 seconds =============================
The terminal process "C:\Users\gorzy\.platformio\penv\Scripts\pio.exe 'run'" terminated with exit code: 1.`

Removing GrayOLED gives me:
`> Executing task: C:\Users\gorzy\.platformio\penv\Scripts\pio.exe run <

Processing lolin_d32 (platform: espressif32@1.11.1; board: lolin_d32; framework: arduino)
----------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin_d32.html
PLATFORM: Espressif 32 (1.11.1) > WEMOS LOLIN D32
HARDWARE: ESP32 160MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)        
PACKAGES: 
 - framework-arduinoespressif32 2.10004.191002 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 33 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <GxEPD> 3.1.0+sha.39621c2
|   |-- <SPI> 1.0
|   |-- <Adafruit GFX Library> 1.10.3+sha.58606c5
|   |   |-- <SPI> 1.0
|-- <Adafruit GFX Library> 1.10.3+sha.58606c5
|   |-- <SPI> 1.0
|-- <Button2> 1.0.0+sha.1d44a26
|-- <ESP8266Audio> 1.7.0+sha.dd8ac07
|   |-- <SPI> 1.0
|   |-- <SPIFFS> 1.0
|   |   |-- <FS> 1.0
|   |-- <HTTPClient> 1.2
|   |   |-- <WiFi> 1.0
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|   |-- <FS> 1.0
|   |-- <SD(esp32)> 1.0.5
|   |   |-- <FS> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Config>
|-- <SPI> 1.0
|-- <Wire> 1.0.1
|-- <HTTPClient> 1.2
|   |-- <WiFi> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|-- <SD(esp32)> 1.0.5
|   |-- <FS> 1.0
|   |-- <SPI> 1.0
|-- <SPIFFS> 1.0
|   |-- <FS> 1.0
|-- <Config>
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <WiFi> 1.0
Building in release mode
Compiling .pio\build\lolin_d32\src\main.cpp.o
Compiling .pio\build\lolin_d32\lib9a8\Adafruit GFX Library@src-ac08a74c2b277f63bd79d3b6a68484c8\Adafruit_GFX.cpp.o
src\main.cpp: In function 'uint32_t skip(WiFiClient&, int32_t)':
src\main.cpp:154:15: warning: unused variable 'v' [-Wunused-variable]
       int16_t v = client.read();
               ^
src\main.cpp: In function 'bool parsePathInformation(char*, char**, char*, unsigned int*, bool*)':
src\main.cpp:241:27: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
     host[hostname_length] = NULL;
                           ^
src\main.cpp: In function 'void handleWebToDisplay(char*, String, bool)':
src\main.cpp:427:58: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
             uint32_t got = read(client, input_buffer, get);
                                                          ^
src\main.cpp:163:10: note: candidate 1: uint32_t read(WiFiClient&, uint8_t*, int32_t)
 uint32_t read(WiFiClient& client, uint8_t* buffer, int32_t bytes)
          ^
In file included from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/stdlib.h:11:0,
                 from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/cores/esp32/WString.h:26,
                 from lib/Config/Config.h:1,
                 from src\main.cpp:1:
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/sys/unistd.h:149:32: note: candidate 2: int read(int, void*, size_t)   
 _READ_WRITE_RETURN_TYPE _EXFUN(read, (int __fd, void *__buf, size_t __nbyte ));        
                                ^
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/_ansi.h:65:30: note: in definition of macro '_EXFUN'
 #define _EXFUN(name, proto)  name proto
                              ^
src\main.cpp:431:76: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
               uint32_t gotmore = read(client, input_buffer + got, get - got);
                                                                            ^
src\main.cpp:163:10: note: candidate 1: uint32_t read(WiFiClient&, uint8_t*, int32_t)   
 uint32_t read(WiFiClient& client, uint8_t* buffer, int32_t bytes)
          ^
In file included from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/stdlib.h:11:0,
                 from C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/cores/esp32/WString.h:26,
                 from lib/Config/Config.h:1,
                 from src\main.cpp:1:
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/sys/unistd.h:149:32: note: candidate 2: int read(int, void*, size_t)   
 _READ_WRITE_RETURN_TYPE _EXFUN(read, (int __fd, void *__buf, size_t __nbyte ));
                                ^
C:/Users/gorzy/.platformio/packages/framework-arduinoespressif32@2.10004.191002/tools/sdk/include/newlib/_ansi.h:65:30: note: in definition of macro '_EXFUN'
 #define _EXFUN(name, proto)  name proto
                              ^
src\main.cpp:509:77: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint32_t {aka unsigned int}' [-Wformat=]
     bytes_read,millisBmp-millisIni, millisEnd-millisBmp, millisEnd-millisIni);
                                                                             ^
src\main.cpp:341:14: warning: unused variable 'creatorBytes' [-Wunused-variable]
     uint32_t creatorBytes = read32(client);
              ^
src\main.cpp:274:12: warning: unused variable 'startTime' [-Wunused-variable]
   uint32_t startTime = millis();
            ^
src\main.cpp:494:28: warning: 'colored' may be used uninitialized in this function [-Wmaybe-uninitialized]
           else if (colored && with_color)
                            ^
src\main.cpp:490:11: warning: 'whitish' may be used uninitialized in this function [-Wmaybe-uninitialized]
           if (whitish)
           ^
Compiling .pio\build\lolin_d32\lib911\ESP8266Audio\libflac\cpu.c.o
Compiling .pio\build\lolin_d32\lib911\ESP8266Audio\libflac\fixed.c.o
In file included from .pio\libdeps\lolin_d32\ESP8266Audio\src\libflac\cpu.c:34:0:
lib/Config/config.h:8:1: error: unknown type name 'String'
 String bearer1 = "cb79cd9e55121ff8f90a28c1ee8353dc53dc27131d87_YOUR_TOKEN";
 ^
lib/Config/config.h:8:18: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
 String bearer1 = "cb79cd9e55121ff8f90a28c1ee8353dc53dc27131d87_YOUR_TOKEN";
Compiling .pio\build\lolin_d32\lib911\ESP8266Audio\libflac\float.c.o
                  ^
lib/Config/config.h:11:1: error: unknown type name 'String'
Compiling .pio\build\lolin_d32\lib911\ESP8266Audio\libflac\format.c.o
 String bearer2 = "";
 ^
lib/Config/config.h:11:18: warning: initialization makes integer from pointer without a 
cast [-Wint-conversion]
 String bearer2 = "";
                  ^
lib/Config/config.h:14:1: error: unknown type name 'String'
 String bearer3 = "";
 ^
lib/Config/config.h:14:18: warning: initialization makes integer from pointer without a 
cast [-Wint-conversion]
 String bearer3 = "";
                  ^
lib/Config/config.h:22:1: error: unknown type name 'uint64_t'
 uint64_t DEEPSLEEP_SECONDS = 3600*3; // Ex. 3 hours
 ^
lib/Config/config.h:44:1: error: unknown type name 'uint8_t'
 uint8_t eink_rotation=3;
 ^
lib/Config/config.h:77:1: error: unknown type name 'int8_t'
 int8_t EINK_CS = 5;
 ^
lib/Config/config.h:78:1: error: unknown type name 'int8_t'
 int8_t EINK_RST  = 16;
 ^
lib/Config/config.h:79:1: error: unknown type name 'int8_t'
 int8_t EINK_DC   = 17;
 ^
lib/Config/config.h:80:1: error: unknown type name 'int8_t'
 int8_t EINK_BUSY = 4;  
 ^
*** [.pio\build\lolin_d32\lib911\ESP8266Audio\libflac\cpu.c.o] Error 1
============================== [FAILED] Took 8.86 seconds ==============================
The terminal process "C:\Users\gorzy\.platformio\penv\Scripts\pio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
`

**Comment by martinberlin** [comment]
Hi,
Just go to .piolibdeps and find the Adafruit library and delete this file.
 This is a problem with Adafruit GFX dependency. The only way to solve it would be to fork it and remove this file.
Tell me if it worked.

**Comment by gorzynsk** [comment]
I admit I cluttered my comment. There were two logs from compilation. One with GrayOled, and second one showing errors after removing GrayOled files.

**Comment by martinberlin** [comment]
Sorry to be more clear, delete both the cpp and the header file:
Adafruit_GrayOLED.h -> delete
Adafruit_GrayOLED.cpp -> delete

If this is an annoyance I will just fork Adafruit and completely wipe out this two.
![platformio_adafruit_delete_2_FILES](https://user-images.githubusercontent.com/2692928/101882553-5610b200-3b96-11eb-9e5a-712aecd70bf1.PNG)

**Comment by martinberlin** [comment]
Alternatively this can be solved adding:
https://github.com/adafruit/Adafruit_BusIO.git

Just pushed it to the master branch. Just reopen if still does not compile!

**Comment by gorzynsk** [comment]
I have to miss some step because compilation still fails. I would be grateful for checking my list.

- have clean workspace in VScode with Platformio installed
- use git clone of [https://github.com/martinberlin/eink-calendar.git](https://github.com/martinberlin/eink-calendar.git)
- switch to `cale_t5` branch
- rename Config.h.dist to Config.h
- uncomment `#define GDEH0213B72  // 2.13" b/w new panel`
- click compile
- remove `Adafruit_GrayOLED.h` and `Adafruit_GrayOLED.cpp` (there are 4 copies - in Adafruit GFX and Adafruit GFX@...)
- compile again

By looking at your screenshot I noticed:
- my log does not contain any "FrameworkArduino" 
- .pio/libdeps contain esp32 folder and not lolin_d32

Here are my logs and screen:

[cale_t5_compilation_log.txt](https://github.com/martinberlin/eink-calendar/files/5708893/cale_t5_compilation_log.txt)

![cale_t5_compilation_screenshot](https://user-images.githubusercontent.com/3940526/102480562-bbfead00-4060-11eb-9a68-4c1651c551c8.png)

**Comment by martinberlin** [comment]
>lib/Config/config.h:11:1: error: unknown type name 'String'
 String bearer2 = "";

Strange, I don't get that!
Anyways let's try something simpler, use branch :+1:

**Comment by martinberlin** [comment]
Didn't had any more feedback so I'm clossing here. If you want to add something please reopen
