### ISSUE TITLE
T5-4.7" instructions

### ISSUE THREAD

**Issue by jasonmhite** [martinberlin/eink-calendar#20]
The list [here](https://cale.es/eink-displays#recommended) suggests that the 4.7" variant of the Lilygo T5 is supported, but I can't seem to figure out to properly configure things for it. I tried following the configuration for the regular T5 without any success... from the serial output it builds and connects to the API properly but I don't get any display output. I gather that the 4.7" version has a different controller than the smaller T5's. 

Could you provide some guidance on what needs to be done to configure for this board?

**Comment by martinberlin** [comment]
Hallo Jason,
You are talking about the 4.7 parallel Model?

That one is not supported by this, only the smaller T5 that are SPI. Sorry is confusing because Lilygo use T5 name for many models. For the EPD47 parallel please use:

https://github.com/vroland/epdiy

Is a very nice component and also has arduino-ESP32 support. Check the readme since it also has a Slack channel to get support.

**Comment by jasonmhite** [comment]
Yeah, that's the one. The cale docs kind of bounce you back and forth, it's a bit confusing. I'll check out the repo you linked, thanks for having a look!

**Comment by martinberlin** [comment]
True I need to find time to reorganize this. @jasonmhite 
Don’t forget that on Cale.es you need to add the API in the screen 
On **screen** menu go to “Partials” and add the crypto API to your template. Then you should be able to preview it when you render the screen.

**Comment by dnwk** [comment]
The document mentioned I could use EPDiy library in Arduino IDE. I haven't figure out how to make it work. Any instructions?

**Comment by martinberlin** [comment]
@dnwk for EPDiy library please reference the component itself:'
https://github.com/vroland/epdiy

This repository has anything to do with Arduino IDE and it's only for ESP-IDF.
