### ISSUE TITLE
Avalibility of pre-built units

### ISSUE THREAD

**Issue by mds08011** [martinberlin/eink-calendar#21]
I'm sorry for asking this this question as a Github issue, but my email to support@cale.es was undeliverable.

Are any of the pre-built units shown on https://cale.es/epapers-for-sale still for sale?

**Comment by martinberlin** [comment]
No problem, you can contact me at martin@cale.es 
There are some units still there. Write me an email and I send you more information.

You can also alternatively use my email in my github profile!
